from __future__ import annotations

from .models import SearchPlan
from .openai_client import OpenAIClient
from .prompts import run_prompt_json
from .query import QueryUnderstanding


def make_plan(
    understanding: QueryUnderstanding,
    max_papers: int,
    since_year: int | None,
    client: OpenAIClient | None,
    seed_search_terms: list[str] | None = None,
) -> SearchPlan:
    seed_search_terms = seed_search_terms or []
    fallback = SearchPlan(
        original_keyword=understanding.original_keyword,
        recommended_query=understanding.recommended_query,
        search_queries=_merge_queries(seed_search_terms, understanding.search_terms[:5] or [understanding.recommended_query]),
        subtopics=understanding.possible_interpretations[:6],
        since_year=since_year,
        max_papers=max_papers,
        notes=["Generated by deterministic fallback planner."],
    )
    if not client or not client.available:
        return fallback
    payload = run_prompt_json(
        client,
        "planner",
        fallback=fallback.to_dict(),
        understanding=understanding.to_markdown(),
    )
    return SearchPlan(
        original_keyword=understanding.original_keyword,
        recommended_query=str(payload.get("recommended_query") or fallback.recommended_query),
        search_queries=_merge_queries(seed_search_terms, list(payload.get("search_queries") or fallback.search_queries))[:12],
        subtopics=list(payload.get("subtopics") or fallback.subtopics)[:8],
        since_year=since_year,
        max_papers=max_papers,
        notes=list(payload.get("notes") or fallback.notes),
    )


def _merge_queries(*groups: list[str]) -> list[str]:
    merged: list[str] = []
    seen: set[str] = set()
    for group in groups:
        for query in group:
            normalized = " ".join(str(query).split())
            key = normalized.lower()
            if normalized and key not in seen:
                merged.append(normalized)
                seen.add(key)
    return merged
